In [26]:
import numpy as np 

a = np.loadtxt("data_raw/LAFAN1_Retargeting_Dataset/g1/dance1_subject1.csv", delimiter=",", max_rows=20, skiprows=1*20)
i = 0
for row in a:
    print(row[0])
    i+=0
    if i>10:
        break

-0.004826
-0.004758
-0.004679
-0.0046
-0.004539
-0.004501
-0.004485
-0.004488
-0.004508
-0.004539
-0.004574
-0.004609
-0.004641
-0.00467
-0.004696
-0.004715
-0.004729
-0.004733
-0.004727
-0.004712


In [1]:
import torch 
w, x, y, z = 1.0, 0.0, 0.0, 0.0
b = torch.tensor([w,x,y,z], dtype=torch.float32)
b.unbind(-1)

n = None
c = n or "cpu"
c

'cpu'

In [3]:
pipi = 5

print(f"{pipi=}")

pipi=5


In [18]:
import torch 

test = torch.randint(
    low=0, high=10, size=(3,2)
)
test2 = test.unsqueeze(dim=1)

a = test.unsqueeze(dim=1)
b = test2
torch.cat((a, b), dim=-1), a

(tensor([[[4, 2, 4, 2]],
 
         [[4, 1, 4, 1]],
 
         [[9, 9, 9, 9]]]),
 tensor([[[4, 2]],
 
         [[4, 1]],
 
         [[9, 9]]]))

In [ ]:
dataset = ["a", "b", "c", "d", "e"]
gabbibbo = dataset[2:] + dataset[0:2]
print(gabbibbo)
a = []

for g in dataset: 
    a.append(gabbibbo.index(g))
a

['c', 'd', 'e', 'a', 'b']
['d' 'e' 'a' 'b' 'c']


In [10]:
import torch 
a = [1,2,3,5]
a = torch.tensor(a)[[0,0,-1,-1]]

a

tensor([1, 1, 5, 5])

In [2]:
import pandas as pd
path_new = "/home/valerio/g1_hybrid_prior/data_raw/LAFAN1_Retargeting_Dataset/g1_ee_augmented/dance1_subject2.csv" 

df = pd.read_csv(path_new, header=None)
print(f"Shape del file processato: {df.shape}")
print(df.head(3))
path_original = "/home/valerio/g1_hybrid_prior/data_raw/LAFAN1_Retargeting_Dataset/g1/dance1_subject2.csv" 
df_original = pd.read_csv(path_original, header=None)
print(df_original.head(3))
print(f"Shape file originale: {df_original.shape}")

Shape del file processato: (3945, 48)
         0         1         2         3         4         5         6   \
0  0.000606 -0.000128  0.779868  0.003238  0.023534 -0.070976  0.997195   
1  0.000565 -0.000134  0.778505  0.004976  0.026533 -0.073249  0.996948   
2  0.000248 -0.000043  0.778132  0.005937  0.029475 -0.075353  0.996704   

         7         8         9   ...        38        39        40       41  \
0 -0.190791  0.179874  0.319062  ...  1.170720  0.055620 -0.531334  1.14534   
1 -0.203150  0.188144  0.333717  ...  1.162653  0.071904 -0.527681  1.13501   
2 -0.209719  0.189649  0.339086  ...  1.159472  0.080153 -0.524429  1.13077   

         42        43        44        45        46        47  
0 -0.012442  0.144493  0.039736 -0.039628 -0.153014  0.037411  
1 -0.012813  0.145644  0.040226 -0.042226 -0.153339  0.037051  
2 -0.013211  0.146026  0.040288 -0.043560 -0.153350  0.036611  

[3 rows x 48 columns]
         0         1         2         3         4         5     